# Generated by Django 6.0.4 on 2026-04-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='component_type',
            field=models.CharField(blank=True, choices=[('', 'Not a build component'), ('cpu', 'CPU'), ('gpu', 'GPU'), ('ram', 'RAM'), ('storage', 'Storage'), ('motherboard', 'Motherboard'), ('psu', 'PSU'), ('case', 'Case'), ('cooler', 'CPU Cooler'), ('other', 'Other')], default='', help_text='Used by the AI Builder / Calculator', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='ram_type',
            field=models.CharField(blank=True, help_text='RAM type (DDR4, DDR5) — fill for RAM and Motherboards', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='socket',
            field=models.CharField(blank=True, help_text='CPU socket (e.g. AM5, LGA1700) — fill for CPUs and Motherboards', max_length=50),
        ),
        migrations.AddField(
            model_name='productreview',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional photo of received product', null=True, upload_to='reviews/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='compatible_with',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/main/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wattage',
            field=models.PositiveIntegerField(blank=True, help_text='Power draw in watts', null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
